version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: analogo
      MYSQL_USER: analogo
      MYSQL_PASSWORD: analogo
      MYSQL_ROOT_PASSWORD: root

  web:
    image: php:7.3.16-apache
    domainname: venganza-analogo.test
    container_name: venganza-analogo.test
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - .:/var/www/html/
      - ./php-settings:/usr/local/etc/php/conf.d
      - ./apache-conf/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
