version: '3'

services:
  db:
    image: mysql:5.7
    container_name: uiofxco-db
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: uiofxco
      MYSQL_USER: uiofxco
      MYSQL_PASSWORD: uiofxco
      MYSQL_ROOT_PASSWORD: root

  web:
    image: php:7.3.16-apache
    domainname: uiofxco.test
    container_name: uiofxco.test
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - .:/var/www/html/
      - ./php-settings:/usr/local/etc/php/conf.d
      - ./apache-conf/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
